name: Terraform Lint

on:
  push:
    branches-ignore:
      - main

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate terraform configuration
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: terraform validate
        uses: dflook/terraform-validate@36ef08d500fe2cd9b742b10176d2683707c7074e # v3

  fmt-check:
    runs-on: ubuntu-latest
    name: Check formatting of terraform files
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: terraform fmt
        uses: dflook/terraform-fmt-check@5702d43749973bd5b54e2380f090c1ad8054ecd4 # v3
