name: Terraform Test

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    name: Integration test
    env:
      TERRAFORM_PRE_RUN: |
        apt-get update
        apt-get install -y zip

    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: terraform test
        uses: dflook/terraform-test@c93c831b1e16d9079520513bb5591a2d8b1d7718 # v3
